### ISSUE TITLE
Provide Java version of this gem

### ISSUE THREAD

**Issue by n-rodriguez** [GlobalNamesArchitecture/damerau-levenshtein#15]
Hi there!

It could be nice to have a Java version of this gem. See https://commons.apache.org/sandbox/commons-text/jacoco/org.apache.commons.text.similarity/LevenshteinDistance.java.html for example.

Thank you!

**Comment by n-rodriguez** [comment]
Or https://github.com/crwohlfeil/damerau-levenshtein

**Comment by dimus** [comment]
It would be good for JRuby projects, yes. It is not on my priorities at the moment, and I did not use JRuby for very very long time If someone who does use it could provide a PR, would be great.
