### ISSUE TITLE
damerau_levenshtein.so LoadError

### ISSUE THREAD

**Issue by Bortechino** [GlobalNamesArchitecture/damerau-levenshtein#20]
I have the message:

> ~/.gem/ruby/2.7.0/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein.rb:4:in `require_relative': libruby.so.2.5: cannot open shared object file: No such file or directory - ~/.gem/ruby/2.7.0/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein/damerau_levenshtein.so (LoadError)

System - ArchLinux.
Ruby 2.7.0
Although the file is present in my system
~/.gem/ruby/2.7.0/gems/damerau-levenshtein-1.3.3/lib/damerau-levenshtein/damerau_levenshtein.so

**Comment by dimus** [comment]
I am trying it on ArchLinux 
```bash
> uname -a
Linux gnlap 5.9.11-arch2-1 #1 SMP PREEMPT Sat, 28 Nov 2020 02:07:22 +0000 x86_64 GNU/Linux
> rbenv version
2.7.2 (set by /home/dimus/.rbenv/version)
> ruby  -rdamerau-levenshtein -e 'puts DamerauLevenshtein.distance("one", "onne")'
1
```
May be some path issue?

**Comment by Bortechino** [comment]
It seems to be some versions' error. The linter is trying to find libruby.so.2.5. There are libruby.so.2.7.2 in the system
[alen@alen-endeavour ~]$ ls -l /lib/libruby*
lrwxrwxrwx 1 root root      16 окт  2 17:56 /lib/libruby.so -> libruby.so.2.7.2
lrwxrwxrwx 1 root root      16 окт  2 17:56 /lib/libruby.so.2.7 -> libruby.so.2.7.2
-rwxr-xr-x 1 root root 3426776 окт  2 17:56 /lib/libruby.so.2.7.2

I'll try to solve the problem with  linter.
Many Thanks!
